name: Sync README to Another Repo

on:
  push:
    paths:
      - 'Nadri/**'   # 이 경로가 변경되었을 때만 동작
    branches:
      - main                     # main 브랜치에서만 동작

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      # 1) 소스 저장소(현재 리포지토리) 체크아웃
      - name: Check out source repository
        uses: actions/checkout@v3

      # 2) Git 사용자 정보 설정
      - name: Set up Git config
        run: |
          git config --global user.name "hwakyung99"
          git config --global user.email "hwakyung5531@gmail.com"

      # 3) 타겟 저장소(Nadri) 복제 후 README.md 복사/커밋/푸시
      - name: Clone target repository and sync README
        env:
          PAT: ${{ secrets.HWAKYUNG_TOKEN }}
        run: |
          # 타겟 저장소를 로컬에 복제
          git clone https://hwakyung99:${PAT}@github.com/hwakyung99/nadri-back-end.git ../backend-reop
          git clone https://hwakyung99:${PAT}@github.com/hwakyung99/nadri-front-end.git ../frontend-reop

          # 소스 리포지토리의 README.md를 타겟 리포지토리 루트로 복사
          cp ./Nadri/README.md ../backend-reop/README.md
          cp ./Nadri/README.md ../frontend-reop/README.md
          cp -r ./Nadri/readme_assets ../backend-reop/
          cp -r ./Nadri/readme_assets ../frontend-reop/

          # backend-reop 커밋 및 푸시
          cd ../backend-reop
          git add *
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Sync README from hwakyung99 repository"
            git push origin main
          fi

          # frontend-reop 커밋 및 푸시
          cd ../frontend-reop
          git add *
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Sync README from hwakyung99 repository"
            git push origin main
          fi